name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Eclipse Temurin JDK
          java-version: '8'
          cache: 'maven'  # Caches Maven dependencies

      - name: Build, Run Unit Tests and create distributions
        run: mvn clean package

      - name: Run E2E tests in GMT timezone
        run: mvn -Duser.timezone=GMT failsafe:integration-test failsafe:verify

      - name: Run E2E tests in non GMT timezone
        run: mvn -Duser.timezone=GMT+0100 failsafe:integration-test failsafe:verify
